### ISSUE TITLE
ShopDelta is set before fetching shops on first run

### ISSUE THREAD

**Issue by koenkarsten** [Adyen/adyen-mirakl#171]
When running the Adyen Mirakl Connector for the first time the connector doesn't register any shop changes, even if no shops have been synced from Mirakl to Adyen before. This is due to the shop_delta in H2 being set to the current timestamp upon initialization, after which the connector asks for any changes since that timestamp, which will result in 0 changes. 

The current workaround I use to get the connector up and running is clearing the shop_delta table after initialization, but this should be fixed in code to allow for a smoother experience when someone starts using this connector.

**Comment by pandemicGander** [comment]
There is a configuration to change this `initialDeltaDaysBack`:

```application:
    miraklPullCron: "0 */1 * * * ?"
    emailRetryCron: "0 */10 * * * ?"
    removeSentEmailsCron: "0 0 2 * * ?"
    payoutRetryCron: "30 1 * * * ?"
    retryDocsCron: "0 */1 * * * ?"
    #how many dates back shall be initially used for updated_at Mirakl queries
    initialDeltaDaysBack: 0```

see `application.yml`

**Comment by koenkarsten** [comment]
Great, I didn't spot this configuration option before. Thanks!
