### ISSUE TITLE
ShareHolder date of birth is -1 day

### ISSUE THREAD

**Issue by koenkarsten** [Adyen/adyen-mirakl#172]
When adding editing a new shareholder, the connector will forward the date of birth in Mirakl -1 day, for example: If the date of birth is set to 20-06-2018 in Mirakl this will be converted to 19-06-2018 in Adyen.

**Comment by rikterbeek** [comment]
Hi @koenkarsten,

That is strange as we just port the data from Mirakl to Adyen.
If you do a manual API call to Mirakl do you see the data as 20-06-2018 or 19-06-2018 ?

Regards,
Rik
Adyen

**Comment by koenkarsten** [comment]
As mentioned by @rikterbeek , the date is displayed incorrectly by Mirakl. The front-end and API dates are 1 day apart, will close this issue and contact Mirakl about this!
