### ISSUE TITLE
Support New Invoice 'Paid' Feature

### ISSUE THREAD

**Issue by rmcotton** [Adyen/adyen-mirakl#205]
Its now possible to flag an invoice as paid with IV07.  https://developer.mirakl.net/api/operator/current/api/IV07.html

https://help.mirakl.net/Customers/topics/Mirakl/integrating_mirakl/pay_sellers/payment_confirmation.htm

This will serve as a good feature once the connector has successfully issued a payout to execute this for all invoices linked to the payment voucher.

**Comment by rkewlani** [comment]
Hi @rmcotton,
Thanks for writing to us. We will check on this and keep you posted about progress.

Regards,
Rajni
Adyen

**Comment by rikterbeek** [comment]
Hi @rmcotton,

I am closing the issue as we not actively improving the connector at this moment.

Regards,
Rik
Adyen
